<li><a href="index.php">Home</a></li>
<li><a href="forums/">Forums</a></li>
<li><a href="index.php">Dashboards</a></li>
<li><a href="index.php">Settings</a></li><!--
<li><a href="index.php">Link5</a></li>
<li><a href="index.php">Link6</a></li>
<li><a href="index.php">Link7</a></li>
<li><a href="index.php">Link8</a></li>
<li><a href="index.php">Link9</a></li> -->